#!/usr/bin/env python

import getopt
import json
import os
import requests
import sys

##Pastes things to zifb.in
def paste(expire=None, language=None):
    """Pastes things to https://zifb.in

usage: cat file | zifbin -e <seconds> -l <language>
e: If specified, expire in this many seconds
l: If specified, use this language for display"""
    ##Read config from .zifb.in.rc (if it exists)
    try: 
        json_config=open(os.path.expanduser('~')+'/.zifbin.rc', "r").read()
        config = json.loads(json_config)
    except Exception as e:
        config = {}


    url = 'https://zifb.in/api/v1/paste'
    data = ''
    
    for line in sys.stdin:
        data += line
    payload = {'paste': data}
    if 'api_key' in config and config.get('api_key') is not None:
        payload['api_key'] = config.get('api_key')
    if 'domain' in config and config.get('domain') is not None:
        payload['domain'] = config.get('domain')

    if expire:
        payload['expiration'] = expire
    else:
        payload['expiration'] = config.get('expiration') if 'expiration' in config else 0
    
    if language:
        payload['language'] = language
        
    r = requests.post(url, data=json.dumps(payload))
    
    output = json.loads(r.text)
    
    if 'error' in output:
        print('Error: {0}'.format(output.get('error')))
    elif 'paste' in output:
        print(output.get('paste'))

if __name__ == '__main__':
    try:
        opts, args = getopt.getopt(sys.argv[1:], "e:l:h")
    except getopt.GetoptError as err:
        print(str(err))
        print(paste.__doc__)
        sys.exit(2)

    expire = None
    language = None

    for o,a in opts:
        if o == '-h':
            print(paste.__doc__)
            sys.exit()
        elif o == '-e':
            expire = a
        elif o == '-l':
            language = a
    paste(expire, language)
